In [1]:
import numpy as np

In [4]:
#regression model that predicts housing prices based on size of the house in sq feets,number of bedrooms,numbers of floors and age
#dataset
x_train=np.array([[2104, 5, 1, 45],[1416, 3, 2, 40],[852, 2, 1, 35]],dtype='int32')
y_train=np.array([460,232,178],dtype='float')


In [11]:
print(f"Shape of features vector {x_train.shape} and type {type(x_train)}")
print(x_train)
print(f"Shape of output vector {y_train.shape} and type {type(y_train)}")
print(y_train)

Shape of features vector (3, 4) and type <class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Shape of output vector (3,) and type <class 'numpy.ndarray'>
[460. 232. 178.]


In [12]:
#storing parameter vector w ,b initial values
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [13]:
#prepare prediction model
def predict(x,w,b):
    p=np.dot(x,w)+b
    return p


In [18]:
#make a prediction
x_1=x_train[0]
print(x_1)

print(f"predicted value {predict(x_1,w_init,b_init)}")

[2104    5    1   45]
predicted value 459.9999976194083


In [21]:
#computing cost for multiple features
def compute_cost(x,y,w,b):
    m=x.shape[0]
    cost=0

    for i in range(m):
        f_wb_i=np.dot(x[i],w)+b
        cost=cost+(f_wb_i-y[i])**2
    cost=cost/(2*m)
    return cost

In [22]:
#computing cost with pre defined parameters
print(f"cost : {compute_cost(x_train,y_train,w_init,b_init)}")

cost : 1.5578904428966628e-12


Gradient descent with multiple regression